# Generated by Django 4.1.6 on 2023-02-10 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('Assam', 'Assam'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], max_length=500)),
                ('Ciity', models.CharField(choices=[('', ''), ('', ''), ('', ''), ('', '')], max_length=500)),
                ('Incentive_Expected', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Phone', models.CharField(max_length=10)),
                ('Skill_certificates', models.FileField(upload_to='Skill_certificates/')),
                ('ID_Proof', models.FileField(upload_to='ID_Proof/')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Type_of_User', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Request', 'Request')], max_length=500)),
                ('Type_of_disaster', models.CharField(choices=[('Agricultural diseases & pests', 'Agricultural diseases & pests'), ('Damaging Winds', 'Damaging Winds'), ('Drought and water shortage', 'Drought and water shortage'), ('Earthquakes', 'Earthquakes'), ('Emergency diseases (pandemic influenza)', 'Emergency diseases (pandemic influenza)'), ('Extreme heat', 'Extreme heat'), ('Floods and flash floods', 'Floods and flash floods'), ('Hail', 'Hail')], max_length=500)),
                ('Rehabilitation_Recovery_estimated_time_in_days', models.IntegerField()),
                ('Service_Domain', models.CharField(choices=[('Financial Aid', 'Financial Aid'), ('Medical Aid', 'Medical Aid'), ('Rehabilitation(Shelter) Aid', 'Rehabilitation(Shelter) Aid'), ('Resources Aid(Food,and other amenities)', 'Resources Aid(Food,and other amenities)'), ('Man-Power', 'Man-Power')], max_length=500)),
                ('Pair_Found', models.BooleanField(default=False)),
                ('Paired_with', models.CharField(max_length=500)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
