# Generated by Django 4.1.6 on 2023-03-11 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
