# Generated by Django 4.1.6 on 2023-03-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_profiles_paired_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Name',
            field=models.CharField(default='DEFAULT', max_length=100),
        ),
    ]
