# Generated by Django 4.1.6 on 2023-02-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Ciity',
            field=models.CharField(choices=[('M', 'M'), ('A', 'A'), ('E', 'E'), ('R', 'R')], max_length=500),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='Paired_with',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
